language: cpp
sudo: required
dist: trusty
python:
  - "3.6"
branches:
    only:
        - develop
        - /^develop-.*$/
        - master
        - release

install:
    - pip3 install tcore
    - tcore bootstrap
    - tcore compile --target stm32f4_disc
    - tcore compile --target tiva_tm4c_launchpad

script:
  - mkdir build
  - cd build
  - nix-shell ../core --pure --run "cmake -DCMAKE_TOOLCHAIN_FILE=../core/toolchains/arm-cm4-gnu.cmake ../"
  - nix-shell ../core --pure --run make
